import { Chewy } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const chewy = Chewy({
  weight: '400', // Chewy only has one weight, which is 400
  subsets: ['latin'], // Specify the subset(s) you want to use
  variable: "--chewy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${chewy.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
